### ISSUE TITLE
Tag with version

### ISSUE THREAD

**Issue by saward** [JSurf/docker-rpi-mariadb#2]
Hi,

Would you please consider adding a tag for the specific MariaDB version(s) that are available?  That way we don't need to rely on 'latest' and risk being upgraded to a newer major release.

Thanks!

**Comment by JSurf** [comment]
Actually i don't really know what version gets installed because this image just uses the latest mariadb package which is available via the official raspbian repositories.

I could create tags for the underlying raspbian version. "jessie", "stretch" and so on. 
I think raspbian/debian stays at the same major version for mariadb for every raspbian version, so this should prevent accidental upgrades

Would this work for you ?

**Comment by saward** [comment]
That sounds like a good solution, thanks.

**Comment by JSurf** [comment]
Just created the tags, there is now latest (=jessie), jessie and stretch
Images shoukld be available on Docker Hub soon
